# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Owner.destroy_all
PlantType.destroy_all
Plant.destroy_all


o1 = @owner = Owner.create!(username: "john123", password: "123" )
o2 = @owner = Owner.create!(username: "bruno123", password: "123" )
o3 = @owner = Owner.create!(username: "daemon_duck", password: "123" )
o4 = @owner = Owner.create!(username: "rockababy", password: "123" )
o5 = @owner = Owner.create!(username: "bellzabub", password: "123" )
o6 = @owner = Owner.create!(username: "cookarina", password: "123" )

pt1 = @plant_type = PlantType.create!(species: "Spider Plant", img_url: "https://bloomscape.com/wp-content/uploads/2019/05/bloomscape-product-spider-plant-indigo-2-1140x1382.jpg", bio: "The Spider plant is among the most adaptable houseplant and very easy to grow. A graceful plant that makes a statement anywhere—from a tabletop to a mantle, or with its lovely arching leaves as a hanging plant. The Spider Plant is also known for its tremendous air purifying qualities, making it a healthy addition to your home as well. Native to tropical and southern Africa, Spider plants have a reputation for being nearly impossible to kill. These fast-growing, fun plants are a great option for the first-time plant owner.", light: "Low")
pt2 = @plant_type = PlantType.create!(species: "Snake Plant", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_snake-plant-laurentii_variant_small_prospect_blush_1024x.jpg", bio: "Native to arid regions of India, Sansevieria zeylanica is a species of snake plant characterized by its dark green variegation. Snake plants are tropical plants that are also succulents. Often positioned as low light plants, they are actually medium to bright light plants that tolerate, but not thrive in low light. Like other succulent plants, they have a modified form of photosynthesis, where in order to preserve water, the plant opens its pores exclusively at night. However, since photosynthesis only happens with daylight, the plant stores carbon dioxide acquired at night for use during the day, and releases oxygen (one of the end products of photosynthesis) at night when the pores open. This helps it to maximize efficiency in cleaning the air, as found in study conducted by NASA.", light: "Low")
pt3 = @plant_type = PlantType.create!(species: "Monstera Deliciosa", img_url: "https://bloomscape.com/wp-content/uploads/2019/04/bloomscape_product-monstera-slate.jpg", bio: "Monstera deliciosa is a species of evergreen tropical vine that is a part of Araceae, the aroid family. Native to the Tropical Americas, it is one of the few aroids which produces edible fruit, hence the species epithet deliciosa. However, it's incredibly rare that a Monstera will flower or produce fruit indoors. Instead, this plant is famous for its beautiful broad green leaves with natural leaf-holes, called fenestrations, which have led to the rise of its nickname, ‘swiss cheese plant’. These holes are theorized to maximize sun fleck capture on the forest floor by increasing the spread of the leaf while decreasing the mass of leaf cells to support.", light: "Medium")
pt4 = @plant_type = PlantType.create!(species: "Philodendron Lemon Lime", img_url: "https://bloomscape.com/wp-content/uploads/2019/12/bloomscape_product_philodendron-lemon-lime_slate-1140x1391.jpg", bio: "The Philodendron Lemon Lime is a fast-growing, easy, vining plant. Its graceful, heart-shaped leaves are bright yellow/green, giving it its name “Lemon Lime”. Native to Africa and the Canary Islands, the Heartleaf can be grown as a trailer or climber. This full, trailing plant is perfect for the top of a bookshelf or in a plant hanger where its vines can cascade. The Philodendron Lemon Lime is incredibly forgiving and will tolerate all kinds of neglect including low light, poor soil, and inconsistent watering. This is a great first-time houseplant or gift for anyone who wants to enjoy the natural beauty of plants without a lot of maintenance.", light: "Medium")
pt5 = @plant_type = PlantType.create!(species: "Lucky Money Tree", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_money-tree_featured_768x.jpg", bio: "Pachira is a genus of evergreen tropical trees native to the neotropics. They belong to the family Malvaceae, the cotton and hibiscus family. This plant seems to come to the houseplant world in a fog of mystery. Known by many names — money tree, water chestnut, guinea nut, and so many more — this plant seems to have found its way into every plant shop around. Like any plant that’s bred for commercial or ornamental purposes, one of the key features of a wanted plant is a plant that is prolific, easy to grow, and tolerant of varying conditions. These plants are actually quite weedy in the tropics, often being grown as erosion-control trees.", light: "Medium")
pt6 = @plant_type = PlantType.create!(species: "Marble Queen Pothos", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_pothos-marble-queen_variant_small_hyde_cream_1024x.jpg", bio: "Epipremnum aureum, or Pothos, is a tropical aroid vine in the family Araceae and native to French Polynesia. Like other closely-related aroids, this plant's leaves will change in shape with age (similar to a Monstera). The leaves can be found in the wild sprawled out along the ground and climbing up trees. Considered to be in the monstera subfamily Monsteroideae, these plants can truly grow monsterous! In mature plants, the leaves can grow to be longer than 3 feet long. Pothos have the ability to spontaneously generate variegation, which has led to several cultivars of variegation and color – classic jade, marble, and neon.", light: "Low")
pt7 = @plant_type = PlantType.create!(species: "Red Maranta", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_maranta_featured_768x.jpg", bio: "The Maranta (Maranta leucomeura) is a pet-friendly prayer plant known for its dramatic foliage. Native to the tropical forests of Brazil, the maranta is most at home in indirect bright light and slightly higher humidity. If your maranta fades in color or becomes washed out, it might be receiving too much direct sun. Marantas (and their family members, calatheas) are often called 'prayer plants' because of their unique leaf movements — they raise and lower their leaves from day to night as a part of their circadian rhythm. This phenomenon is called nyctinasty. Plant movements are controlled by a flux of water pressure in the pulvini (nodes at the base of the leaves). Scientists theorize that these movements are meant to follow the sun and catch as much light as possible — an essential trait for a forest-floor-dwelling plant.", light: "Medium")
pt8 = @plant_type = PlantType.create!(species: "Bird's Nest Fern", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_birds-nest-fern_variant_small_grant_black_1024x.jpg", bio: "Asplenium nidus is most commonly referred to as the Bird’s Nest Fern. In the wild, this fern grows everywhere: on trees and on the ground. Descended from an ancient lineage of plants, these plants never flower or produce seeds. Instead, they sporulate to reproduce! Spores are generated from leaf tissue. All plants that sporulate love moisture and can tolerate being perpetually moist (but not wet). It is theorized that in later plants, flowers and cones evolved from modified sporulating leaf structures.", light: "Medium")
pt9 = @plant_type = PlantType.create!(species: "ZZ Plant", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_large-zz-plant_featured_768x.jpg", bio: "Zamioculcas zamiifolia, affectionately called the ZZ plant or Zanzibar Gem, is a tropical plant in the aroid family, Araceae. It is native to Zanzibar, Kenya, and Eastern Africa. You might spot large potato-like rhizomes under the surface of its potting mix. Having evolved in drier conditions than most other aroids, these plants have evolved rhizomes that store water to help the ZZ plant survive drought in its natural environment. The rhizomes are actually underground stems, and what you see above ground are the stems' leaves. Using these underground rhizomes, the plant slowly creeps over time to new locations, spawning new aboveground leaves along the way.", light: "Medium")
pt10 = @plant_type = PlantType.create!(species: "Calathea Rattlesnake", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_calathea-rattlesnake_variant_small_grant_blush_1024x.jpg", bio: "Calathea lancifolia, the Rattlesnake Calathea, is a colorful member of the prayer plant family, Marantaceae. Calatheas are often called 'prayer plants' because of their unique leaf movements: they raise and lower their leaves from day to night as a part of their circadian rhythm. This phenomenon is called nyctinasty. Plant movements are controlled by a flux of water pressure in the pulvini - nodes at the base of the leaves. Scientists theorize that these movements are meant to follow the sun and catch as much light as possible –– an essential trait for a forest-floor-dwelling plant!", light: "Medium")
pt11 = @plant_type = PlantType.create!(species: "Parlor Palm", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_parlor-palm_featured_768x.jpg", bio: "Chamaedorea elegans, also known as the Neanthe Bella Parlor Palm, is one of our favorite true palms. With the right care and many, many repottings, the Parlor Palm can grow to well over six feet tall. But do not repot more than once a year, as their roots like to relax. Although in the same family as coconuts and dates, which produce edible fruit from flowers at the top of the plant, this plant produces inedible fruit from flowers at the base of the plant. It most likely will not flower indoors, but it will bring a tropical feel to any space. Cultivated since the Victorian era, this species of palm is prized for its resilience to indoor conditions and reliable habit.", light: "High")
pt12 = @plant_type = PlantType.create!(species: "Alocasia Polly", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_alocasia-polly_featured_3900ac92-b029-4f87-824b-2572823bf7fa_768x.jpg", bio: "The Alocasia Polly is a cultivar of alocasia which has become known as the African mask plant or elephant ear plant because of its striking shape. It has broad, dark green leaves with bright white contrasting veins. Native to southeast Asia and Australia, alocasia are aroids in the family, Araceae, and are related to many other common houseplants.", light: "High")
pt13 = @plant_type = PlantType.create!(species: "Xerographica Air Plant", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_xerographica-airplant_featured_768x.jpg", bio: "Tillandsia xerographica is a dry-forest epiphyte in the bromeliad family, Bromeliaceae. As an epiphyte, it grows on top of tree branches and pulls all the water it needs from the intense morning fogs of its native habitat. These fogs naturally dry up by midday, and the plant collects nutrients from the desert dust that blows around to sustain itself. Like other bromeliads, it grows from a central rosette, radiating out its leaves. This growth is slow, taking years to reach its maximum 3 feet in diameter. Tillandsia are also monocarpic, meaning that once it flowers it dies, but not before producing pups (baby air plants) at their base.", light: "Medium")
pt14 = @plant_type = PlantType.create!(species: "Marimo Moss Ball", img_url: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_marimo-moss-ball_featured_4cabf512-a7e2-4855-acad-a97056eeed1f_768x.jpg", bio: "The Marimo ‘Moss’ Ball is a fuzzy aquatic ball of filamentous green algae. It thrives without much light in a freshwater aquarium or clear container with filtered water.  This houseplant is pet friendly!", light: "Medium")
pt15 = @plant_type = PlantType.create!(species: "Hoya Heart Plant", img_url: "https://i.etsystatic.com/10494852/r/il/575b33/1981736562/il_794xN.1981736562_hbk8.jpg", bio: "Hoya kerrii, or Hoya Hearts, are tropical succulent vines that are often cultivated and sold as leaf cuttings. They belong to the Dogbane family, Apocynaceae, which includes some notable plants such as Dogbane, Oleander, Plumeria, Periwinkle, Golden Trumpet, and Mandevilla.  Plants in Apocynaceae have latex sap, are usually fragrant, and are high in alkaloids (esp. Iridoids).  The aromatic compounds produced by the flowers are prized as fragrances in perfumes, and the flowers are also cultivated as ornamentals in warmer climates. Hoya flowers are fragrant and waxy-looking, with the fragrance changing with the age of the flower.", light: "Medium")


p1 = @plant = Plant.create!(name: "Hairy Styles", owner: o1, plant_type: pt1)
p2 = @plant = Plant.create!(name: "Cactus Perry", owner: o2, plant_type: pt2)
p3 = @plant = Plant.create!(name: "Berry White", owner: o2, plant_type: pt2)
p4 = @plant = Plant.create!(name: "Bitty Spears", owner: o2, plant_type: pt6)
p5 = @plant = Plant.create!(name: "Georgia O'Keefe", owner: o3, plant_type: pt6)
p6 = @plant = Plant.create!(name: "Urusla", owner: o3, plant_type: pt1)
p7 = @plant = Plant.create!(name: "Big poppa", owner: o3, plant_type: pt3)
p8 = @plant = Plant.create!(name: "B I G", owner: o4, plant_type: pt3)
p9 = @plant = Plant.create!(name: "Tupac", owner: o5, plant_type: pt1)
p10 = @plant = Plant.create!(name: "Leo DiCappitate", owner: o6, plant_type: pt6)
p11 = @plant = Plant.create!(name: "Bernard", owner: o5, plant_type: pt6)
p12 = @plant = Plant.create!(name: "Jack", owner: o5, plant_type: pt1)
p13 = @plant = Plant.create!(name: "Leona", owner: o6, plant_type: pt2)
p14 = @plant = Plant.create!(name: "Cousin Vinny", owner: o6, plant_type: pt3)